#!/usr/bin/env sh

# Pre-build environment configuration and checks
src_env ()
{
        return 0
}

# Prepare stow package and do any necessary patching or fixes
src_prepare ()
{
        cp -f -- "${KEYDIR}/config.mk" "./config.mk"
}

# Configure and build the stow package
src_build ()
{
        local _c

        for _c in dark light
        do
                cp -f -- "${KEYDIR}/solarized-${_c}-config.h" "./config.h"
                make
                mv -f -- st "st-${_c}"
        done

        tic -sx st.info
}

# Run pre-install test scripts
src_check ()
{
        return 0
}

# Install the stow package
src_install ()
{
        make PREFIX="$DESTDIR" install
        mv -f -- st-* "${DESTDIR}/bin"
}

# Called before stow package is stowed
stow_prae ()
{

        return 0
}

# Called after stow package is stowed
stow_post ()
{
        return 0
}

# Called before stow package is unstowed
unstow_prae ()
{
        return 0
}

# Called after stow package is unstowed
unstow_post ()
{
        return 0
}

# vim: set ft=sh ts=8 sw=8 tw=0 et :
