#!/bin/sh

# Pre-build environment configuration and checks
src_env ()
{
        return 0
}

# Prepare stow package and do any necessary patching or fixes
src_prepare ()
{
        mkdir -p -- "${XDG_VAR_HOME}/mail/queue"
        chmod 0700 -- "${XDG_VAR_HOME}/mail/queue"
}

# Configure and build the stow package
src_build ()
{
        return 0
}

# Run pre-install test scripts
src_check ()
{
        return 0
}

# Install the stow package
src_install ()
{
        command install -D -m 755 scripts/msmtpq/msmtp-queue "${DESTDIR}/${XDG_BIN_HOME#$HOME}/msmtp-queue"
        command install -D -m 755 scripts/msmtpq/msmtpq "${DESTDIR}/${XDG_BIN_HOME#$HOME}/msmtpq"

        cd -- "${DESTDIR}/${XDG_BIN_HOME#$HOME}"

        ed -s msmtpq <<S
/^Q=.*$/s/.*/Q=\$Q/
/^LOG=.*$/s/.*/LOG=\$LOG/
/^EMAIL_CONN_TEST=[xpPns]$/s/.*/EMAIL_CONN_TEST=\$EMAIL_CONN_TEST/
w
S

        ed -s msmtp-queue <<S
2i
export Q=\${XDG_VAR_HOME}/mail/queue
export LOG=\${XDG_VAR_HOME}/log/msmtp-queue.log
export EMAIL_CONN_TEST=P
.
w
S
}

# Called before stow package is stowed
stow_prae ()
{

        return 0
}

# Called after stow package is stowed
stow_post ()
{
        return 0
}

# Called before stow package is unstowed
unstow_prae ()
{
        return 0
}

# Called after stow package is unstowed
unstow_post ()
{
        return 0
}

# vim: set ft=sh :
